name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # 1. Перевірка помилок у HTML коді
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run HTML Hint
        run: |
          npm install -g htmlhint
          htmlhint index.html

  # 2. Збірка Docker-образу та відправка на GitHub
  build-and-push:
    needs: linter 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Твій нік та назва проекту прописані вручну:
          tags: ghcr.io/totaltarizm/project3:latest

  # 3. Запуск сайту та 3-х тестів k6
  test-quality:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Start Container
        run: |
          # Запускаємо сайт на порту 8081
          docker run -d -p 8081:80 --name test_app ghcr.io/totaltarizm/project3:latest
          sleep 10 # Чекаємо, поки сайт завантажиться
      - name: Run k6 Tests
        uses: grafana/k6-action@v0.3.1
        with:
          filename: load-test.js
      - name: Cleanup
        if: always()
        run: docker rm -f test_app || true