name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ] # Запуск при кожному пуші в гілку main
  pull_request:
    branches: [ "main" ] # Запуск при створенні Pull Request

jobs:
  # ЕТАП 1: Лінтер (Перевірка якості HTML-коду)
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6 # Копіюємо файли репозиторію на раннер

      - name: Run HTML Hint
        run: |
          npm install -g htmlhint
          htmlhint index.html # Перевірка на синтаксичні помилки в HTML

  # ЕТАП 2: Збірка образу та публікація в реєстр (GHCR)
  build-and-push:
    needs: linter # Запускається тільки якщо лінтер пройшов успішно
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Дозвіл на запис у GitHub Container Registry
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true # Відправляємо зібраний образ у хмару
          tags: ghcr.io/totaltarizm/project3:latest

  # ЕТАП 3: Тестування розгорнутого застосунку
  test-quality:
    needs: build-and-push # Чекаємо, поки образ з'явиться в реєстрі
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Website Container
        run: |
          # Запускаємо контейнер із сайтом, відкриваючи порт 8081
          docker run -d --name test_app -p 8081:80 ghcr.io/totaltarizm/project3:latest
          sleep 10 # Пауза, щоб Nginx встиг піднятися

      - name: Run k6 Load Test
        # Запускаємо k6 у Docker через network=host для прямого доступу до localhost:8081
        run: |
          docker run --rm --network host -i -v ${{ github.workspace }}:/io -w /io grafana/k6 run load-test.js

      - name: Cleanup
        if: always() # Виконується навіть якщо тести впали
        run: docker rm -f test_app || true # Видаляємо контейнер після тестів