name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run HTML Hint
        run: |
          npm install -g htmlhint
          htmlhint index.html

  build-and-push:
    needs: linter 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # v5 або v7 (перевірена версія)
        with:
          context: .
          push: true
          tags: ghcr.io/totaltarizm/project3:latest

  test-quality: # Тепер відступ правильний (на рівні з іншими jobs)
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start Container for Testing
        run: |
          # Видаляємо старий, якщо він раптом лишився, і запускаємо новий
          docker rm -f test_app || true
          docker run -d -p 8081:80 --name test_app ghcr.io/totaltarizm/project3:latest
          sleep 10 # Даємо Nginx трохи більше часу на старт

      - name: Run k6 Tests
        uses: grafana/k6-action@v0.3.1
        with:
          filename: load-test.js
          flags: --network=host # Додаємо, щоб k6 бачив localhost контейнера

      - name: Stop and Cleanup
        if: always()
        run: docker rm -f test_app || true